version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3001:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    build:
      context: ./database
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"

