version: '3'

services:
  httpd-blue:
    build:
      context: ./blue
        #ports:
      #- "8081:80"

  httpd-purple:
    build:
      context: ./purple
        # ports:
      #- "8082:80"
  
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - httpd-blue
      - httpd-purple
